version: '3.8'
services:
  web:
    build: Dockerfile
    ports:
      - '5000:5000'
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: flask_db